- vagrant/README.md
adding some info on the project (following questions from @drigodwin this morning) and using it to test the new repo structure.
> add usage info to vagrant sub-project

- packaging/pom.xml
- packaging/src/conf/brooklyn.conf
- packaging/src/conf/logback.xml
- packaging/src/service/brooklyn.service
RPM packaging proposal. Tested on Centos 7 and RHEL 7 systems.
> Add RPM packaging

- LICENSE
- all/pom.xml
- dist/licensing/extras-files
- dist/licensing/licenses/brooklyn-client/ASL2
- dist/licensing/licenses/rest-server/ASL2
- dist/licensing/licenses/source/ASL2
- dist/licensing/make-all-licenses.sh
- dist/licensing/make-one-license.sh
- dist/licensing/overrides.yaml
- dist/licensing/projects-with-custom-licenses
- dist/pom.xml
- dist/src/main/config/build-distribution.xml
- dist/src/main/license/files/LICENSE
Merge this after the following are merged:
https://github.com/apache/brooklyn-client/pull/4
https://github.com/apache/brooklyn-server/pull/54
https://github.com/apache/brooklyn-ui/pull/15
https://github.com/apache/brooklyn-docs/pull/25
https://github.com/apache/brooklyn/pull/5
> Include brooklyn-client-cli

- packaging/pom.xml
- pom.xml
Adding packaging as module to brooklyn-dist pom.xml.
Also fixing version and artifact name.
> Add packaging to pom modules, fix version

- dist/licensing/overrides.yaml
To be merged **after** https://github.com/apache/brooklyn-ui/pull/17
> Add UI library reference for licensing purposes

- packaging/pom.xml
- packaging/src/service/brooklyn.service
@alrick87 @rdowner can you take a look please? Really want this fix in before 0.9.0 release candidate!
> Fix RPM log dir

- archetypes/quickstart/src/brooklyn-sample/src/main/resources/catalog.bom
- archetypes/quickstart/src/brooklyn-sample/src/test/resources/sample.bom
- shared-packaging/src/test/yaml/package.bom
- vagrant/src/main/vagrant/files/vagrant-catalog.bom
- vagrant/src/main/vagrant/servers.yaml
See related changes in https://github.com/apache/brooklyn-docs/pull/82
> Catalog format more consistent

- karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.osgilauncher.cfg
The default value has changed to AUTO, this should be reflected in the commented setting
> Update persistMode default value

- release/Vagrantfile
- release/clone-and-configure-repos.sh
- release/environment.sh
- release/gpg-agent.conf
- release/make-release-artifacts.sh
Updates made to support the release of 0.9.0.
> Release script updates

- dist/src/main/license/files/LICENSE
Merge after https://github.com/apache/brooklyn-server/pull/457
> Upgrade LICENSE jclouds version

- karaf/features/src/main/feature/feature.xml
Depends on https://github.com/apache/brooklyn-server/pull/334
> Upgrade to Karaf 4.0.8

- docker-itest/Dockerfile
- docker-itest/entrypoint.sh
Run with:
```
docker run --rm -v $(pwd):/build \
-v ~/.m2/repository/:/maven-repo  \
-e DOCKER_USER_ID=$(id -u) -e DOCKER_GROUP_ID=$(id -g)  \  --> use this line only on linux machines
brooklyn-itest \
mvn -B clean install -PIntegration -Dmaven.test.failure.ignore=true --fail-never
```
> A Docker container to run integration tests in

- downstream-parent/pom.xml
Related to https://github.com/apache/brooklyn-server/pull/741
> Update maven-compiler-plugin to 3.6.1

- karaf/config/pom.xml
> Remove another reference to a deleted file.

- karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.logging.cfg
- karaf/pom.xml
(see https://github.com/apache/brooklyn-server/pull/771)
> Updates due to karaf update to 4.1.2

- vagrant/src/main/vagrant/README.md
- vagrant/src/main/vagrant/files/brooklyn.service
- vagrant/src/main/vagrant/files/install_brooklyn.sh
Take only the changes from #105 which change for Karaf. Tested on local and snapshot releases.
> Make vagrant work for Karaf

- deb-packaging/pom.xml
- rpm-packaging/pom.xml
I missed to add those files in #104, as it is required for releases
> Add LICENSE and NOTICE file back to the RPM and DEB packages

- release/verify_brooklyn_rc.sh
This does the following things:
- improve the readability of the script
- ignore the NOTICE/LICENSE files check for the DEB package (as there is no reliable way of getting the content of that archive)
> Improve verify brooklyn RC script

- dist/licensing/overrides.yaml
as per https://github.com/apache/brooklyn-server/pull/885
> add license info for icons added to brooklyn-server project

- karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.logging.cfg
See https://github.com/apache/brooklyn-server/pull/940 for details
> Add MDC to pax logging config

- all/pom.xml
- depends on https://github.com/apache/brooklyn-server/pull/830
> fix dependencies for brooklyn-all

- dist/pom.xml
- docker-image/Dockerfile
- docker-image/README.md
- docker-image/pom.xml
- pom.xml
Incorporates and addresses review comment in #136
Moves version to brooklyn-server/pom.xml
Requires https://github.com/apache/brooklyn-server/pull/1023
> Docker build plugin version

- Dockerfile
- Jenkinsfile
- docker-itest/Jenkinsfile
With this, the multi branch job on Jenkins (to be created) finally works! 🎉
> Add jenkinsfile for multibranch job on Jenkins

- karaf/features/src/main/feature/feature.xml
- karaf/itest/pom.xml
- karaf/pom.xml
Several dependency versions updated to fix known vulnerabilities.
See https://github.com/apache/brooklyn-server/pull/1140
> Bumping depencencies

- karaf/features/src/main/resources/resources/etc/org.ops4j.pax.logging.cfg
> Added sample configuration for trace log

- Jenkinsfile
- docker-itest/Jenkinsfile
Signed-off-by: Mykola Mandra <mykola.mandra@cloudsoft.io>
> Use double quotes to resolve DOCKER_TAG

- DEPENDENCIES
- dist/licensing/license-text/CC0 1.0 Universal
- dist/src/main/license/files/LICENSE
- dist/src/main/license/files/NOTICE
- karaf/features/src/main/resources/resources/LICENSE
- karaf/features/src/main/resources/resources/NOTICE
Updated licences ahead of release
> Updated licenses
