apache/brooklyn-dist

LICENSE
dist/licensing/overrides.yaml
dist/src/main/license/files/LICENSE

Relates to https://github.com/apache/brooklyn-ui/pull/1

Updated to licence overrides for codemirror (JSGUI)

---

all/pom.xml

This change is required in support of https://github.com/apache/brooklyn-library/pull/1.

Add entry for Salt integration.

---

vagrant/src/main/vagrant/servers.yaml

- see https://bugs.launchpad.net/ubuntu/+bug/1553119
Confirmed this stands up as expected, and deployed the Template 4: Resilient Load-Balanced Bash Web Cluster with Sensors example

switch to wily64 - vivid64 ubuntu box no longer available

---

all/pom.xml

so could not deploy ansible entities.
This permits blueprints with AnsibleEntity to deploy.

AnsibleEntity was missing from 'all' pom.xml

---

pom.xml

Add a build flag "-Dno-rpm" and profile to allow configuration of build to avoid RPM packaging step.

Add build flag (& profile)  "-Dno-rpm" 

---

packaging/pom.xml

Our RPM package is marked as `noarch`. RPM will complain if it finds architecture-specific files in `noarch` package - therefore it complains for us due to the presence of the `br` tool in multiple architectures.  This commit turns off that test.

Set RPM option to allow binaries in noarch package

---

packaging/pom.xml

Fixing the bug with incorrect file permissions on config files in `/etc/brooklyn/` directory.

Fix config file permissions

---

downstream-parent/pom.xml

they are all pulled in from the parent (brooklyn-server/pom.xml, except for jackson which we don't want to declare as we don't use it.
sidebar comment, i now tend to the opinion that we *don't* want this.  downstream projects should define their own workflow. the main value is ensuring versions are compatible but that is something we can/should handle a different way. (simple way, just by running the license-audit plugin and eyeball anything with multiple versions...)
/cc @neykov @aledsage @hzbarcea wdyt?

remove the properties section from this file

---

vagrant/src/main/vagrant/Vagrantfile
vagrant/src/main/vagrant/servers.yaml

- brooklyn accessible on the local node (desktop/laptop where you have run `vagrant up`) via mapped `8081` port at `http://127.0.0.1:8081` which matches the manual install url (simplifies docs)
- can still access the byon nodes on `10.10.10.x` and avoids having to worry about subnet clashes for brooklyn itself

use host only networking for brooklyn node

---

archetypes/quickstart/src/brooklyn-sample/src/main/resources/catalog.bom

The PR adds updates to the existing jars to add a catalog.bom file that includes the details of the various entities in each.  
See https://github.com/apache/brooklyn-server/pull/80 for details; this PR depends on that one and should be merged after it.

Populate catalog from bundle bom

---

release/change-version.sh

`target` folders are already excluded in the find command. Remove call to `mvn clean` because the project could hit unresolved dependencies (in the case of using a custom repo location). Also speeds up the execution.

Don't run mvn in change-version.sh

---

dist-karaf/apache-brooklyn/pom.xml
dist-karaf/apache-brooklyn/src/main/filtered-resources/etc/branding.properties
dist-karaf/apache-brooklyn/src/main/resources/etc/custom.properties
dist-karaf/apache-brooklyn/src/main/resources/etc/default.catalog.bom
dist-karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.core.catalog.bomscanner.cfg
dist-karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.osgilauncher.cfg
dist-karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.logging.cfg
dist-karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.url.mvn.repositories.cfg
dist-karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.web.cfg
dist-karaf/apache-brooklyn/src/main/resources/etc/system.properties
dist-karaf/itest/pom.xml
dist-karaf/itest/src/test/java/org/apache/brooklyn/AssemblyTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/KarafTestUtils.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScannerTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/core/catalog/internal/DefaultBomLoadTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/rest/BrooklynRestApiLauncherTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/security/CustomSecurityProvider.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/security/CustomSecurityProviderTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/security/StockSecurityProviderTest.java
dist-karaf/itest/src/test/java/org/apache/brooklyn/test/IntegrationTest.java
dist-karaf/itest/src/test/resources/custom-security-bp.xml
dist-karaf/itest/src/test/resources/exam.properties
dist-karaf/itest/src/test/resources/logback.xml
dist-karaf/pom.xml
pom.xml

This PR is the third of three that together move the karaf distribution to brooklyn-dist and separate out the software from brooklyn-library into separate catalog bom and feature files.
Merge this after https://github.com/apache/brooklyn-library/pull/53.

Move karaf distribution to brooklyn-dist.

---

karaf/apache-brooklyn/src/main/resources/etc/org.apache.karaf.shell.cfg
karaf/features/src/main/feature/feature.xml

After the changes three ports remain open:
* 8081 - web UI, password is generated on the fly if not explicitly set by the user
* 8101 - ssh Karaf access, protected by default credentials, open to localhost only
* random - jmx port, enabled by "-Dcom.sun.management.jmxremote" in bin/karaf, allows local access only
* random - shutdown port

Close public ports protected by the default credentials

---

archetypes/quickstart/pom.xml
archetypes/quickstart/src/brooklyn-sample/pom.xml
archetypes/quickstart/src/main/resources/META-INF/maven/archetype-metadata.xml
archetypes/quickstart/src/test/resources/projects/integration-test-1/archetype.properties

If archetypeRepository is set when using the quickstart archetype,
then add that URL to the pom.xml. This allows a customer’s private
maven artifactory to be used for accessing timestamped builds of
Brooklyn (for example).

Make archetypeRepository configurable

---

archetypes/quickstart/pom.xml
archetypes/quickstart/src/brooklyn-sample/pom.xml
archetypes/quickstart/src/test/resources/projects/integration-test-1/archetype.properties

Fixes the following test error on windows:
```
[INFO] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project brooklyn-sample: Execution default of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process failed: Target host is null -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process (default) on project brooklyn-sample: Execution default of goal org.apache.maven.plugins:maven-remote-resources-plugin:1.5:process failed: Target host is null
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoEx …
```

Fix archetype test on Windows.

---

archetypes/quickstart/pom.xml
archetypes/quickstart/src/brooklyn-sample/src/main/resources/catalog.bom

Previously was 0.10.0-SNAPSHOT, but this is the version of the user’s
project rather than brooklyn.
Also removes the apache header because this is a starting point for
a user to create their own projects (which will not necessarily be
apache licensed). This starting file is extremely basic; it is a file
without any degree of creativity.

archetype’s catalog.bom set up as 0.1.0-SNAPSHOT

---

karaf/apache-brooklyn/src/main/resources/etc/org.ops4j.pax.logging.cfg

Also fix missing or invalid log4j.logger prefixes to packages, change the logging layout to be more compact (no fixed widths)

Silence Karaf dist brooklyn.info.log

---

shared-packaging/src/test/yaml/Vagrantfile
shared-packaging/src/test/yaml/package-apps.yaml
shared-packaging/src/test/yaml/package.bom

Need to update the tests following changes in inheritance
of files.preinstall, see https://github.com/apache/brooklyn-server/pull/281.
This allows the tests defined in package-apps.yaml to work again.  
Caveat: in the apt-upstart test on my machine, the `13. restart machine` step happens so quickly that Brooklyn doesn't even notice that the Vanilla Software Process has gone down, so the step `14. check not running while restarting' fails. Not sure what to do about that; however I have manually tested that Brooklyn comes up again after the restart.

Update tests following changes in files.preinstall inheritance

---

karaf/apache-brooklyn/src/main/resources/bin/setenv

This PR does the following:
- adds a `setenv` script
- sets default memory settings
- checks if java is installed
- sets the local loopback
This PR addresses the following issue https://issues.apache.org/jira/browse/BROOKLYN-348
and ensures karaf scripts don't fail silently if java is not installed.

Added setenv script to karaf bin 

---

karaf/apache-brooklyn/src/main/resources/etc/system.properties

The INFO message `BouncyCastle not registered, using the default JCE provider`
appears in the logs, coming from Karaf's SSH server module (org.apache.sshd.core).
Explicitly prevent sshd from registering BC to suppress the message.

Suppress log message about BouncyCastle in Karaf

---

karaf/apache-brooklyn/src/main/resources/bin/setenv

This PR does the following:
- Adds an OS check to the start of the `setenv` script
- Constructs `JAVA_HOME` based on the OS

Adds OS check to the setenv script

---

dist/src/main/dist/bin/brooklyn
dist/src/main/dist/bin/brooklyn.bat
karaf/apache-brooklyn/src/main/resources/bin/setenv
shared-packaging/src/main/resources/service/systemd/brooklyn.service
shared-packaging/src/main/resources/service/upstart/deb/brooklyn.conf
shared-packaging/src/main/resources/service/upstart/rpm/brooklyn.conf

Adds the java opt `-XX:SoftRefLRUPolicyMSPerMB=1` when launching brooklyn. see [BROOKLYN-375](https://issues.apache.org/jira/browse/BROOKLYN-375) for further details.

Adds SoftRefLRUPolicyMSPerMB

---

karaf/pom.xml

Version 0.12 adds the option to dump licence violations to the console.

Upgrade rat plugin version

---

dist/src/main/license/files/LICENSE

The classic dist (which this LICENSE is for) contains only guava 18.0. So not keeping 16.0.1 in there as well.

Update LICENSE with latest dependency changes

---

karaf/apache-brooklyn/src/main/resources/LICENSE

This adds the LICENSE file for the Karaf distribution.
For the regular distribution this is automated through the Maven
plugin, however for Karaf the process is different as Karaf
assembles dependencies based also on features.
This commit includes a semi-manually generated LICENSE file until
such time as we can create a process for generating the file
automatically.
The process followed is:
1. Build the code.
2. Search the system directory for jar files and extract their
pom.properties:
```
find system -name '*jar' -type f | while read jar ; do
pp=$(jar tf $jar | grep pom.properties)
if [ "$pp" ] ; then
jar xf $jar $pp
else
echo $jar has no pom.properties
fi
done
```
~~TODO~~ (licenses added in updated squashed commit 1/Dec): the above process noted the following jars without …

Add manually created LICENSE file for Karaf distribution.

---

karaf/apache-brooklyn/pom.xml
karaf/features/pom.xml
karaf/pom.xml

Depends on https://github.com/apache/brooklyn-server/pull/479. See it for a detailed description.

Upgrade karaf-maven-plugin to avoid double User-Agent bug

---

karaf/apache-brooklyn/pom.xml

Removes duplicate LICENSE, NOTICE files.

Exclude META-INF folder from Karaf dist

---

karaf/features/src/main/feature/feature.xml

Related to https://github.com/apache/brooklyn-server/pull/481

Reorder `brooklyn-locations-jclouds` so that its installed before library features 

---

karaf/pom.xml

(the ones removed are declared in brooklyn-server/pom.xml)
i see this is also included in #48 but there are now conflicts and this partial improvement can be done now without waiting on that, i think -- @neykov ?

remove unnecessary versions in karaf pom

---

vagrant/src/main/vagrant/files/brooklyn.service
vagrant/src/main/vagrant/files/install_brooklyn.sh
vagrant/src/main/vagrant/servers.yaml

Ubuntu wily is now EOL so move to Xenial LTS and Centos 7 which is better supported by blueprints. Note that to test this, you can use [this commit](https://github.com/apache/brooklyn-dist/pull/67/commits/08aba9135113220fa484cd8649056af789f90878) which includes a hard coded URL and version for Brooklyn.

Replace expired ubuntu default

---

scripts/am

Makes merging Github PRs in the Apache repos easier and less error-prone. Adds more context to the merge commit message - PR title and body.
Create a Github personal token at https://github.com/settings/tokens for smoother experience - see how to use it in sources.

PR merge automation

---

karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.osgilauncher.cfg

default catalog location can now be configured using the below PID
`org.apache.brooklyn.osgilauncher/default.catalog.location`
default has been set as `${karaf.etc}/default.catalog.bom`

Make the default catalog location configurable

---

karaf/apache-brooklyn/src/main/resources/etc/org.apache.brooklyn.classrename.cfg
karaf/itest/src/test/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherTest.java

This adds:
- an empty file for the user to edit
- an integration tests (although, the entire test suite does not work, the setup has some issue that needs to be fixed)

Allow a user to add or override deserialize configuration in karaf

---

karaf/itest/src/test/java/org/apache/brooklyn/launcher/osgi/OsgiLauncherTest.java

The merge of #72 broke [brooklyn-server/#508](https://github.com/apache/brooklyn-server/pull/508) which was then merged shortly after. This PR fixes this.

Fix OsgiLauncherTest

---

karaf/itest/src/test/java/org/apache/brooklyn/AssemblyTest.java
karaf/itest/src/test/java/org/apache/brooklyn/core/catalog/internal/CatalogBomScannerTest.java
karaf/itest/src/test/java/org/apache/brooklyn/security/CustomSecurityProviderTest.java
karaf/itest/src/test/java/org/apache/brooklyn/security/StockSecurityProviderTest.java

Triggered by a refactoring I had to do and missing a bunch of places that needed updating.
* add missing `@Override` annotations
* add missing `@Deprecated` annotations (usually just javadoc `@override` exists)
* remove unused imports
* remove unnecessary casts
Look at each commit individually.
Similar PRs created for the other brooklyn sub-projects.

Add missing @Override annotations and other cleanup

---

downstream-parent/pom.xml
karaf/apache-brooklyn/src/main/resources/etc/system.properties
karaf/features/src/main/feature/feature.xml

Change OSGi feature to load BouncyCastle early, to avoid "Refreshing bundles" later

Load BouncyCastle bundles early on

---

karaf/features/src/main/feature/feature.xml

This builds on Svet's https://github.com/apache/brooklyn-dist/pull/48 (which has now been merged).
It avoids the rewiring of the bundle org.apache.sshd.core, which would otherwise happen when bouncycastle bundles were later installed.
I've been testing it with https://github.com/apache/brooklyn-server/pull/547.

Avoid sshd.core bundle rewiring on startup

---

downstream-parent/pom.xml

`org.apache.http.*` now works fine via `Import-Packages` so shouldn't be excluded, and downstream projects no longer need to do anything special if they use this package space

don't exclude apache http in karaf subprojects

---

dist/licensing/overrides.yaml

provides additional data for https://github.com/apache/brooklyn-server/pull/557

add license items for icons used in brooklyn-server (server from tango project)

---

shared-packaging/src/test/yaml/Vagrantfile
vagrant/src/main/vagrant/servers.yaml

Prior to this PR running the vagrant getting started environment would fall back to using rsync for making the `/vagrant` share available in the guest OS due to the `centos/7` box not including virtualbox guest additions (resulting in the absense of the vboxfs drivers). This would complicate using the vagrant env on Windows where rsync is not available by default. The `centos/X` boxes do not following current best practices for virtualbox providers.
This commit switches to the community managed bentos centos-7.3 box which follows best practices and includes the vbox guest additions. See - https://github.com/chef/bento

switch vagrant boxes to bento images

---

scripts/am

For convenience merging commits into branches apart from master.
Usage:
am 588 0.10.x
will merge 588 from the 0.10.x branch of ${PR_REMOTE}.
The script does not check out the branch!  It requires you to check it out
and verifies that it is on the right branch.  Leaving it like this to enforce
a certain manualness to the procedure, for safety's sake.

Update merge script to support optional non-master branch.

---

docker-itest/Dockerfile

Bump the java version to 8 in light of the projecft's decision to phase away Java 7 support.
Install the chef package, needed by integration tests for the knife executable.

docker-itest: java version to 8, add chef package

---

karaf/features/src/main/feature/feature.xml

Updates namespace on the file to http://karaf.apache.org/xmlns/features/v1.4.0
which is required for 'prerequisite="true"' on feature declarations.

Fix namespace on feature.xml

---

all/pom.xml

Updates the `brooklyn-all` POM to include the new `brooklyn-container-service` code added by https://github.com/apache/brooklyn-server/pull/732

Add the container service dependencies to the main distribution

---

downstream-parent/pom.xml

This is a bundle by now.
This change is required in a downstream project to be able to access GCE correctly from within Karaf.

Don't avoid importing jclouds google compute engine.

---

release/make-release-artifacts.sh

As discussed on the mailing list this PR moves to making the karaf release the primary artifact.

Make karaf release the primary one

---

deb-packaging/pom.xml
karaf/config/pom.xml
karaf/config/src/main/resources/catalog/catalog-core.bom
karaf/config/src/main/resources/catalog/catalog-templates.bom
karaf/config/src/main/resources/catalog/catalog.bom
karaf/features/src/main/feature/feature.xml
rpm-packaging/pom.xml

This reuses each bundle's `catalog.bom` file to build global `catalog.bom`. 
It avoids the duplication of bom files and keep all the metadata (title, description, iconUrl, etc) under the same module that contains the actual Java entity.
It also creates a `brooklyn-catalog` feature for Karaf for downstream project to reuse it, if required.
Those changes spans across `brooklyn-server`, `brooklyn-library` and `brooklyn-dist`. 
This requires (and should be tested with):
- https://github.com/apache/brooklyn-server/pull/834
- https://github.com/apache/brooklyn-library/pull/130

Modular catalog.bom

---

release/Vagrantfile
release/make-release-artifacts.sh

This makes the following changes to the release scripts:
* Fixes a typo in the maven version which is installed
* Doesn't copy over the local gpg keyring to the vagrant box
This is because it just uses the first one and if there are multiple keys on it, the wrong one will probably be used. Just manually copy on the keys (I'll amend the docs to document this).
* Updates the CLI artefacts with new structure
* Fixes the path to the built RPM
* Adds the deb

Fix release scripts

---

vagrant/src/main/vagrant/files/install_brooklyn.sh

The name of the tar.gz archive is different for the dist version (i.e. `apache-brooklyn-<version>-bin`) and therefore, the name of the extracted folder needs to match that.
Based on the mailing list discussion: https://lists.apache.org/thread.html/104010308cf525da847894c4ec543a6f4ab20a6e0bf9212873422cbd@%3Cdev.brooklyn.apache.org%3E

Fix vagrant installation folder when downloading dist version

---

karaf/config/src/main/resources/catalog/catalog-templates.bom

As https://github.com/apache/brooklyn-server/pull/882 now includes the entities from `server-cli`, therefore they need to be removed from here.

Reuse bundle's catalog.bom from server-cli module

---

dist/pom.xml
dist/src/main/config/build-distribution.xml
dist/src/main/dist/conf/brooklyn/default.catalog.bom

This fixes the build for `brooklyn-dist` (i.e. for brooklyn classic mode). I broke it in https://github.com/apache/brooklyn-server/pull/886 when I deleted its `catalog.bom` - this project tries to find that .bom file in mvn! Things seemed to work because local .m2 maven snapshot repos had the old version of that file, but it would fail on a clean machine.
Note that `brooklyn-dist` was crippled by https://github.com/apache/brooklyn-server/pull/882 - that stripped out most things from the brooklyn-cli catalog.bom (by removing `scanJavaAnnotations: true`) so the classic dist only had 4 things in its catalog rather than everything it could find during a scan.
This PR's default.catalog.bom is a copy of the file from before https://github.com/apache/brooklyn-server/pull/882.
Also note that we …

Fix brooklyn-dist (classic) build

---

all/pom.xml

Without the dependency the build does not include the entity images for clusters and servers.

brooklyn-all has a dependency on brooklyn-catalog-aliases

---

karaf/apache-brooklyn/src/main/resources/bin/setenv

Before, java was not refreshing the DNS records, ever. This is due to the default `networkaddress.cache.ttl` set to `-1`, i.e. cache forever.
This PR updates the system property `sun.net.inetaddr.ttl` to `60` by default. It uses `sun.net.inetaddr.ttl` because `networkaddress.cache.ttl` **is not** a system property. But this has the desirable effect (see: https://stackoverflow.com/a/17219327)

[BROOKLYN-579] Add DNS TTL configuration via envvar

---

karaf/apache-brooklyn/src/main/filtered-resources/bin/generate-password.sh

In the classic launcher, one can run `brooklyn generate-password --user <username>` to generate the hashed password to go in brooklyn.cfg, for logging into the web-console.
In brooklyn karaf, that is not supported (so will not be available at all from 1.0.0).
The PR adds a script to generate the hash of a given password.
~~If this looks good to reviewers, then~~ I'll update the brooklyn docs accordingly: https://github.com/apache/brooklyn-docs/pull/259

Add generate-password.sh

---

karaf/features/pom.xml
karaf/features/src/main/feature/feature.xml

See discussion about the donated UI: https://lists.apache.org/thread.html/20d82876f7e84244c2c4d3464a1531a10af50ca3d20e9e1de97a5faf@%3Cdev.brooklyn.apache.org%3E
This replaces the old UI by the new one.
Note that it requires:
- https://github.com/apache/brooklyn-server/pull/974
- https://github.com/apache/brooklyn-library/pull/156
- https://github.com/apache/brooklyn-ui/pull/54

Update Brooklyn codebase to build the newly donated UI

---

karaf/itest/pom.xml

Latest version of Java 1.8.0_191 enforces that Manifest classpath entries be relative.
https://issues.apache.org/jira/browse/SUREFIRE-1588

Fix for SUREFIRE-1588

---

dist/pom.xml
docker-image/Dockerfile
docker-image/README.md
docker-image/pom.xml
pom.xml

To avoid the build failing if Docker is not installed and running,
put the docker image build into a profile, so build with
mvn clean install -Pdocker
This also moves the Dockerfile from `brooklyn-dist/dist` into karaf/apache-brooklyn
so it generates the image from the karaf distro.
We should remove `brooklyn-dist/dist` as well but that can be another PR.
See discussion on https://lists.apache.org/thread.html/f296ff5ed96002f165bdef95d0aac083261ff44c78c24c0a804fe4d9@%3Cdev.brooklyn.apache.org%3E

Avoid build depending on Docker by default

---

karaf/apache-brooklyn/src/main/resources/bin/setenv.bat

Executing on Windows environments throws a `OutOfMemoryError: GC overhead limit exceeded`.
I've solved it locally increasing the memory on `karaf.bat` but is better set up in the `setenv.bat` script.

Set up minimum and max memory for Windows environments

---

dist/pom.xml
docker-image/pom.xml
pom.xml

This disables by default the build of `rpm-packaging`, `deb-package` and `docker-image`. These can be reenabled by doing:
```
mvn clean install -Drpm -Ddeb -Ddocker
```
This is to fix the inconsistency pointed out in this email thread: https://lists.apache.org/thread.html/f296ff5ed96002f165bdef95d0aac083261ff44c78c24c0a804fe4d9@%3Cdev.brooklyn.apache.org%3E
Please note this depends on: https://github.com/apache/brooklyn/pull/30

Make the build of rpm, deb and docker optional by default

---

Jenkinsfile

This should greatly decrease the build time on Jenkins.
See https://builds.apache.org/job/brooklyn-library/job/master/ and https://builds.apache.org/job/brooklyn-client/job/master/ for the decrease of build time (same changes have been merged over there)

Reuse local maven cache + add PR comment trigger 

---

release/environment.sh
release/make-release-artifacts.sh
release/verify_brooklyn_rc.sh

Remove MD5 and SHA-1 for [BROOKLYN-597](https://issues.apache.org/jira/projects/BROOKLYN/issues/BROOKLYN-597)
Merge after https://github.com/apache/brooklyn-ui/pull/160
Also simplifies the artifact signing, just hashing the artifacts and signing only the SHA256SUMS file.
Details per JIRA:
Per the recently updated Apache Release Distribution Policy, https://www.apache.org/dev/release-distribution, we should remove the generation and checking of MD5 and SHA-1 checksums from brooklyn-dist/release before we do another release, presumably 1.0.
The relevant wording is 
For every artifact distributed to the public through Apache channels, the PMC
MUST supply a valid OpenPGP-compatible ASCII-armored detached signature file
MUST supply at least one checksum file
SHOULD supply a SHA-256 and/or …

BROOKLYN-597 Remove md5/sha1

---

dist/src/main/dist/conf/brooklyn/default.catalog.bom
karaf/config/src/main/resources/catalog/catalog-templates.bom

`apt-get install` will try to prompt the user for confirmation when installing a package unless the `-y` parameter is provided. This causes the install to abort is there is no attached terminal.

Don’t prompt for confirmation with apt-get

---

dist/src/main/dist/conf/brooklyn/default.catalog.bom
karaf/config/src/main/resources/catalog/catalog-templates.bom

Changes included:
- added `autoscaler.` in front of autoscaler policy configuration properties in  `3-bash-web-and-riak-template` and `4-resilient-bash-web-cluster-template`
- added comment with recommended OS for the two templates

Added fix for broken templates and OS recommendation

---

karaf/apache-brooklyn/src/main/resources/etc/org.apache.karaf.features.xml

Accompanies https://github.com/apache/brooklyn-server/pull/1092; that PR must be merged first.
Excludes BouncyCastle 1.51 in karaf - using `bundleReplacements` in `org.apache.karaf.features.xml`.
---
I confirmed this works by running the karaf client (`./bin/client`), and looking at:
```
karaf@brooklyn()> feature:info jclouds-services                                                                                                                                                                                 
Feature jclouds-services 2.1.2
Feature contains followed bundles:
...
mvn:org.bouncycastle/bcprov-ext-jdk15on/1.61 (overriden from mvn:org.bouncycastle/bcprov-ext-jdk15on/1.51)
...
karaf@brooklyn()> feature:info jclouds-driver-bouncycastle
Feature jclouds-driver-bouncycastle 2.1.2 …
```

Bump BouncyCastle version: from 1.51 to 1.61

---

karaf/features/src/main/feature/feature.xml

Bundles are stopped / refreshed due to the order that bundles are
being added. This fixes some of those problems.
Requires https://github.com/apache/brooklyn-server/pull/1095 to be merged first.

Fix some karaf startup slowness

---

karaf/apache-brooklyn/pom.xml

Brookyn build is failing when you try to package as RMP: https://ci-builds.apache.org/job/Brooklyn/job/brooklyn/job/master/5/console
The error is
```
Failed while enforcing releasability the error(s) are [
Dependency convergence error for org.javassist:javassist:3.24.0-GA paths to dependency are:
+-org.apache.brooklyn:rpm-packaging:1.1.0-SNAPSHOT
+-org.apache.brooklyn:apache-brooklyn:1.1.0-SNAPSHOT
+-org.apache.karaf.features:enterprise:4.2.8
+-org.hibernate:hibernate-osgi:5.4.8.Final
+-org.hibernate:hibernate-core:5.4.8.Final
+-org.javassist:javassist:3.24.0-GA
and
+-org.apache.brooklyn:rpm-packaging:1.1.0-SNAPSHOT
+-org.apache.brooklyn:apache-brooklyn:1.1.0-SNAPSHOT
+-org.apache.brooklyn:brooklyn-features:1.1.0-SNAPSHOT
+-org.apache.brooklyn:brooklyn-rest-resources:1.1.0-SNAPSHOT …
```

fix javaasist collision

---

karaf/apache-brooklyn/src/main/resources/bin/setenv

JAVA_MAX_PERM_MEM no longer supported by java so removed.
See changes to karaf here https://github.com/apache/karaf/pull/1337

JAVA_MAX_MEM ignored so add to EXTRA_JAVA_OPTS
